spring:
  application:
    name: user-server

server:
  port: 8766

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:4000

ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 2000


