spring:
  application:
    name: myrabbitmq
  rabbitmq:
    host: 192.168.186.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    #确认消息已发送到交换机(Exchange)
    publisher-confirms: true
    #确认消息已发送到队列(Queue)
    publisher-returns: true

server:
  port: 8888





